#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use LaravelHelper\Commands\SetupIDE;
use LaravelHelper\Commands\UpdateIDE;
use Symfony\Component\Console\Application;

$app = new Application('Laravel Helper', '1.0.6');

$app->addCommands([new SetupIDE(), new UpdateIDE()]);

$app->run();
