#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use LaravelHelper\Commands\SetupIDE;
use Symfony\Component\Console\Application;

$app = new Application('Laravel Helper', '0.1');

$app->add(new SetupIDE());

$app->run();
